### ISSUE TITLE
Instant issue with Artifact of Smash

### ISSUE THREAD

**Issue by Darkmega18** [bcs4313/Artifacts-Of-DOOM#2]
I played ridley, and went with the artifact of smash... cause he's based on his incarnation from smash. However as soon as I spawned. I jumped and touched the ground and took damage without being knocked back. and then I went to hit a wisp, and instantly crashed the game. it was a little whack. :<

**Comment by bcs4313** [comment]
Hello!

Sorry to see that you have this issue. I would fix it quickly if I could, but there are some big things that happened with this mod that halted development abruptly.

 A while ago a lost my most recent backup of the mod due to a hard drive failure (git repo is very out of date, missing unity and wwise assets, etc). However, I have found an up to date .dll from someone that I can use to slowly patch it back together. Then I can fix the problem. That work will begin on Friday, the start of spring break. Thank you.

**Comment by Darkmega18** [comment]
Ah. Congrats on getting back up and running.
that all sounds good. Thanks for getting back to me. :)

I hope it goes mostly smoothly.

**Comment by bcs4313** [comment]
Hi again! The decomplication process was successful! For today I'll be working on your suggestions now with the new repo files.

**Comment by bcs4313** [comment]
After some extensive changes / testing, I can conclude that Artifact of Smash no longer causes sudden crashes.
In addition, some parts of the formula have been changed to account for other concerns.
- The threshold for taking damage from impacts is much higher for players, accounting for their jump height. Simply jumping up and down should no longer force players to take damage. 
- Just like in smash, you should take more knockback depending on how low your hp is and how hard you were hit by a monster. 
- I changed the formula a bit to make the artifact less laggy as well.

I've attached a file that you can test out as you please. I will release this once I get some other desired changes together (artifact of war still needs work, still need to regenerate some unity assets)

[csProj.zip](https://github.com/bcs4313/Artifacts-Of-DOOM/files/10977506/csProj.zip)
Just replace the csProj.dll in the "plugins/bcs4313-ArtifactsOfDoom" directory.

**Comment by Darkmega18** [comment]
OOooh, thanks a lot! I'll be sure to give it a shot. :D

also for smash, whatabout being knocked out of a teleport boundary? are you able to detect that and make it so that you instantly die from it? :3 it'd be really funny to see someone hit a grav mine from forgotten relics and go flying out the ceiling and explode.
speaking an accompanying visual only mithrix pizza blast erupting from your death location would be a nice touch to hearken to how a player dies in smash also when getting knocked out. 

But ok, after I'm done testing some other things in other mods and unlock a couple more challenges for gear etc I'll give it a try soonish. :)

**Comment by Darkmega18** [comment]
ok. so this is really funny, but something I'm noticing is that I don't seem to be getting credited for kills?

stuff like killing an enemy with lights out isn't reloading itself, or throwing enemies into walls feels like they aren't dropping gold for me anymore cause they're too far away? I'm not sure what it is though.

**Comment by Darkmega18** [comment]
another thought.
can the velocity be reduced. the the overall actor health be increased so that enemies have more health to be knocked back with? 
the current velocity is pretty strong so any considerable hit is pretty well a one way ticket inside the wall or off into empty space. But if health was upped, higher damage attacks would be less likely to cause as strong of a knockback until enemies are reduced in health, letting you weaken them to then launch them.

also, characters like the executioner and loader tend to hurt themselves easily cause of their reliance on going fast and not taking fall damage when doing certain moves/at all.

**Comment by bcs4313** [comment]
Solving these one at a time.

Players receive credit on world based kills now.

[csProj.zip](https://github.com/bcs4313/Artifacts-Of-DOOM/files/10984620/csProj.zip)

I'll deal with knockback scaling being too high next, then I will solve the loader/executioner problem.

**Comment by bcs4313** [comment]
Actor health was changed:
Enemy health doubled
Survivor health doubled

I added scaling based on the health missing from the player before the hit (so health functions more like percentages in smash), and introduced logarithmic scaling to hits to prevent hard hits at full health from having too extreme knockback.
[csProj.zip](https://github.com/bcs4313/Artifacts-Of-DOOM/files/10986145/csProj.zip)

**Comment by Darkmega18** [comment]
Thanks! I'll give it a go! :D

**Comment by Darkmega18** [comment]
Definitely a lot more balanced and survivable now. :)

**Comment by bcs4313** [comment]
That's great to hear! I'll see what I can do with the loader/executioner problem and then set it up for release.

**Comment by bcs4313** [comment]
I do find the idea of an explosion for being knocked out of bounds really funny, so I'll check to see if I can reliably detect out of bounds knockback.

**Comment by Darkmega18** [comment]
I just wish I could more reliably launch larger foes as their health gets lower.

it's be an interesting side option where the only thing that can kill is being launched into something. so that you can get reduced to one HP, but you actually gotta smash them into a surface hard enough to finish them.

Not sure if you could find a nice explosion that has an eruption on it and orient it based on the surface of impact for the effect. the only one off the top of my head is the mithrix/lunar shockwave, or perhaps the shockwave from the special move that the alloy worship unit does.

**Comment by Darkmega18** [comment]
possibly make the starting line:
"Strange aliens invade your planet in drop-pods? SETTLE IT IN SMASH!"

**Comment by bcs4313** [comment]
I added a way to manually adjust the launch parameters for non-boss monsters, boss monsters, and players. Damage for each can also be adjusted to match your preferences. Hopefully this helps in perfecting the feel of the artifact.

I haven't added the option to have the final blow be from an impact yet, but its doable. I may do it sometime in the future.

I added an explosion on death. I tried doing the mithrix shockwave first but then I realized there are some issues when handling the onDeath effect. There isn't really a quaternion (rotation) that can tell the shockwave how to orient itself, since the impact doesn't really provide any rotation/orientation parameter. 

- The final impact is an electric explosion, scaled up and layered from the jellyfish monster. Hope you like it!

**Comment by Darkmega18** [comment]
oooh. nice. so will this be part of the eventual release? or do you still have some other things to touch up like war?

**Comment by bcs4313** [comment]
These changes are already released. I am going to touch up war later.

**Comment by Darkmega18** [comment]
oop. I'll go right ahead and give it a go then. :D
