### ISSUE TITLE
All but Artifacts of Smash, not appearing?

### ISSUE THREAD

**Issue by Geno2222** [bcs4313/Artifacts-Of-DOOM#4]
Hi! Reporting this issue.
I've tried both Manually and via ModManager, with all the dependencies required, but in both Cases all but the Artifact of Smash will not appear.
The console does show the errors, but i have no idea what may be causing them, i even tried on a "clean" install with no other mods.

For the Manual install i simply: Created "ArtifactOfDoom" Folder in Plugins, and put all the files there.
For the Modmanager, i just let it do its thing.

No luck so far. Here's the log.

[LogOutput.log](https://github.com/bcs4313/Artifacts-Of-DOOM/files/11133401/LogOutput.log)

**Comment by bcs4313** [comment]
I'll check the installation real quick. Sometimes Mods just break on the thunderstore with updates. This may be the case.

**Comment by Geno2222** [comment]
Is the manual install process just: Create folder in Plugins>Put all Files there>Play

Or do i need to set things up any other way? I couldn't find any info on the manual install.

**Comment by bcs4313** [comment]
A fresh install on the thunderstore doesn't cause any issues for me.

According to your log, ScanAllAssemblies fails for the csProj file in my mod, which is linked to MMHOOK (HookGenPatcher).

MMHOOK is a dependency for the mod, so I would guess that even with a clean install the download cache might be putting in a corrupted MMHOOK every time, or MMHOOK's contents are just not there.

You could try resinstalling HookGenPatcher yourself after clicking "Toggle download cache" to disable the cache loading. Or you could do a manual install of the directory I provided to get it working.
[MMHOOK fix.zip](https://github.com/bcs4313/Artifacts-Of-DOOM/files/11133476/MMHOOK.fix.zip)

just throw all the folders contained in the ZIP into the \BepInEx\plugins directory.

**Comment by Geno2222** [comment]
Ok so, after some messing around, i think i've found the issue.

Now, i'm not a modder, not of this game at least, so i could be wrong BUT:

As far as i gathered, there was a mod called Chest QoL, that uses the same "Risk of Option" Api that your mod uses to have adjustable Config in-game.

That mod, did something to the configs and made it so your mod wouldn't be able to run anymore. I don't know how, i don't know why, and sure as hell i don't know how in the fucking world once that mod is removed it STILL causes the issue? (I guess the Configs don't get reverted?) But hey, it works now.

Thanks for your help.
