### ISSUE TITLE
Artifact of Unity bug

### ISSUE THREAD

**Issue by JustDeadweight** [bcs4313/Artifacts-Of-DOOM#7]
Was doing a run with one other person with artifact of unity. He died stage two and respawned on the next stage. Every 5-10 seconds after he respawned he gained several copies of every item I collected while he was dead. Before long he had over 3 thousand items.

**Comment by bcs4313** [comment]
Hello.

That is most certainly unintended. I have two theories as to what caused this. First is that the classes responsible for restoring items don't clear their item storage when the player dies each time (only on stage progression is it cleared). Second is that it's counting items that are received when the player revives, resulting in exponentially higher item duplications.

I'll get to work on fixing it now. Thank you for the detailed response; it makes debugging easier.

**Comment by JustDeadweight** [comment]
Didn't think to mention it earlier as the other issue seemed significantly more important but in the few times we've tried using this artifact, the time this bug occurred is the only time that items received when one player was dead were actually given to the dead player.
The game gave the "{player} (dead) has received {item}" message when the items were obtained but didn't sync properly on moving to a new stage.

**Comment by bcs4313** [comment]
I believe I patched this out in version 1.6. Reopen the issue if this isn't the case.
